package com.mapr.qss.cep.demo.telecom;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("CDR")
public class SimpleCallDetailRecord implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String callingPartyNumber;
   private java.lang.String calledPartyNumber;
   private com.mapr.qss.cep.demo.telecom.CallType callType;
   private java.util.Date prevCalledDate;
   private java.util.Date calledDate;
   private long durationInSeconds;
   private java.lang.String billingPhoneNumber;
   private long sequenceNumber;
   private long siteId;
   private boolean used2Gdata;
   

   public SimpleCallDetailRecord()
   {
   }

   public java.lang.String getCallingPartyNumber()
   {
      return this.callingPartyNumber;
   }

   public void setCallingPartyNumber(java.lang.String callingPartyNumber)
   {
      this.callingPartyNumber = callingPartyNumber;
   }

   public java.lang.String getCalledPartyNumber()
   {
      return this.calledPartyNumber;
   }

   public void setCalledPartyNumber(java.lang.String calledPartyNumber)
   {
      this.calledPartyNumber = calledPartyNumber;
   }
   
   public com.mapr.qss.cep.demo.telecom.CallType getCallType()
   {
      return this.callType;
   }

   public void setCallType(com.mapr.qss.cep.demo.telecom.CallType callType)
   {
      this.callType = callType;
   }

   public java.util.Date getPrevCalledDate()
   {
      return this.prevCalledDate;
   }

   public void setPrevCalledDate(java.util.Date prevCalledDate)
   {
      this.prevCalledDate = prevCalledDate;
   }

   public java.util.Date getCalledDate()
   {
      return this.calledDate;
   }

   public void setCalledDate(java.util.Date calledDate)
   {
      this.calledDate = calledDate;
   }

   public long getDurationInSeconds()
   {
      return this.durationInSeconds;
   }

   public void setDurationInSeconds(long durationInSeconds)
   {
      this.durationInSeconds = durationInSeconds;
   }

   public java.lang.String getBillingPhoneNumber()
   {
      return this.billingPhoneNumber;
   }

   public void setBillingPhoneNumber(java.lang.String billingPhoneNumber)
   {
      this.billingPhoneNumber = billingPhoneNumber;
   }

   public long getSequenceNumber()
   {
      return this.sequenceNumber;
   }

   public void setSequenceNumber(long sequenceNumber)
   {
      this.sequenceNumber = sequenceNumber;
   }

   public long getSiteId()
   {
      return this.siteId;
   }

   public void setSiteId(long siteId)
   {
      this.siteId = siteId;
   }

   public boolean isUsed2Gdata()
   {
      return this.used2Gdata;
   }

   public void setUsed2Gdata(boolean used2Gdata)
   {
      this.used2Gdata = used2Gdata;
   }

   public SimpleCallDetailRecord(java.lang.String callingPartyNumber,
         java.lang.String calledPartyNumber, 
         com.mapr.qss.cep.demo.telecom.CallType callType,
         java.util.Date prevCalledDate,
         java.util.Date calledDate, long durationInSeconds,
         java.lang.String billingPhoneNumber, long sequenceNumber, long siteId,
         boolean used2Gdata)
   {
      this.callingPartyNumber = callingPartyNumber;
      this.calledPartyNumber = calledPartyNumber;
      this.callType = callType;
      this.prevCalledDate = prevCalledDate;
      this.calledDate = calledDate;
      this.durationInSeconds = durationInSeconds;
      this.billingPhoneNumber = billingPhoneNumber;
      this.sequenceNumber = sequenceNumber;
      this.siteId = siteId;
      this.used2Gdata = used2Gdata;
   }

}