package com.mapr.qss.cep.demo.telecom;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sms implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String targetPhoneNumber;
   private java.lang.String message;

   public Sms()
   {
   }

   public java.lang.String getTargetPhoneNumber()
   {
      return this.targetPhoneNumber;
   }

   public void setTargetPhoneNumber(java.lang.String targetPhoneNumber)
   {
      this.targetPhoneNumber = targetPhoneNumber;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public Sms(java.lang.String targetPhoneNumber, java.lang.String message)
   {
      this.targetPhoneNumber = targetPhoneNumber;
      this.message = message;
   }

}